version: "3.8"
services:
  geoserver:
    build: ./geoserver
    volumes:
    - geoserver-data:/var/lib/jetty/webapps/geoserver/data
    ports:
      - "127.0.0.1:8000:8080"
    env_file:
      .env

  db:
    build: ./postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      .env

  app:
    build:
      context: https://github.com/HotMaps/Hotmaps-toolbox-service.git
      dockerfile: ./api/dockerfiles/api/Dockerfile
    expose:
    - 80
    restart: always

  frontend:
    build:
      context: https://github.com/HotMaps/Hotmaps-toolbox-client.git
    expose:
    - 80
    restart: always

volumes:
  db-data:
  geoserver-data:
