version: "3.8"
services:
  geoserver:
    build: ./geoserver
    volumes:
    - geoserver-data:/var/lib/jetty/webapps/geoserver/data
    ports:
    - "8000:8080"

  db:
    build: ./postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  db-data:
  geoserver-data:
