version: "3.8"
services:
  geoserver:
    build: ./geoserver
    volumes:
    - geoserver-data:/var/lib/jetty/webapps/geoserver/data
    ports:
      - "127.0.0.1:8000:8080"
    env_file:
      .env

  db:
    build: ./postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      .env

volumes:
  db-data:
  geoserver-data:
