version: "3.8"
services:
  geoserver:
    build: ./geoserver
    volumes:
    - geoserver-data:/var/lib/jetty/webapps/geoserver/data
    ports:
      - "127.0.0.1:8000:8080"
    env_file:
      .env

  db:
    build: ./postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      .env

  app:
    build:
      context: ../Hotmaps-toolbox-service/api/
    ports:
      - "127.0.0.1:9000:80"
    volumes:
      - upload-data:/var/hotmaps/users
    restart: always
    env_file:
      .env

  redis:
    image: redis

volumes:
  db-data:
  geoserver-data:
  upload-data:
