version: "3.8"
services:
  geoserver:
    image: camptocamp/geoserver:jetty-2.11.2
    volumes:
    - geoserver-data:/usr/local/tomcat/webapps/ROOT/data
    ports:
    - "8000:8080"

  db:
    build: ./postgis
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  db-data:
